### ISSUE TITLE
Feature request: theme selection

### ISSUE THREAD

**Issue by idleberg** [donnierayjones/coderbility#1]
Personally, I prefer dark themes, so I would appreciate an option page that let's a user specify theme (and possibly override fonts settings)

**Comment by donnierayjones** [comment]
Do you switch to the dark option in Readability/Instapaper? I'm thinking I could create an options page which lets you configure two themes: one for bright and one for dark. It would automatically switch when you change the bright/dark option in Readability/Instapaper.

**Comment by idleberg** [comment]
Why not simply offer any of the styles shipping with highlight.js?

**Comment by donnierayjones** [comment]
That's what I was planning, but was thinking it'd be nice to be able to configure one of those styles for the light theme and one for the dark theme.

**Comment by idleberg** [comment]
Oh, I actually forgot that there's a dark theme for Instapaper, wasn't quite sure what you were talking about before. So, yes configuring two themes sounds like a great idea!

**Comment by donnierayjones** [comment]
I just pushed out an update that allows to configure two themes. Let me know if you have any problems with it.

**Comment by idleberg** [comment]
Works great, thank you!
